# Generated by Django 5.2.5 on 2026-06-10 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaCafe',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('numero_ingreso', models.CharField(max_length=50, unique=True)),
                ('fecha_venta', models.DateField()),
                ('empresa_compradora', models.CharField(max_length=150)),
                ('tipo_cafe', models.CharField(choices=[('Cafe pergamino', 'Café pergamino'), ('Cafe oro', 'Café oro'), ('Cafe miel / honey', 'Café miel / honey')], max_length=30)),
                ('procedencia', models.CharField(default='Irupana', max_length=100)),
                ('proveedor', models.CharField(default='La Avanzada', max_length=100)),
                ('cantidad_sacos', models.PositiveIntegerField()),
                ('peso_total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_editadas', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta de café',
                'verbose_name_plural': 'Ventas de café',
                'db_table': 'ventas_cafe',
                'ordering': ['-fecha_venta', '-fecha_registro'],
            },
        ),
    ]
