# Generated by Django 5.2.5 on 2026-06-08 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id_productor', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_productor', models.CharField(max_length=20, unique=True, verbose_name='Código del productor')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido materno')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productores', to='comunidades.comunidad', verbose_name='Comunidad')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productores_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productores_editados', to=settings.AUTH_USER_MODEL, verbose_name='Editado por')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso')),
            ],
            options={
                'verbose_name': 'Productor',
                'verbose_name_plural': 'Productores',
                'db_table': 'productores',
            },
        ),
    ]
