# Generated by Django 5.2.5 on 2026-06-08 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comunidades', '0001_initial'),
        ('productores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraCafe',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField(verbose_name='Fecha de compra')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra por libra')),
                ('total_libras', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de libras')),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total pagado')),
                ('productor_nombre_recibo', models.CharField(max_length=300, verbose_name='Productor en recibo')),
                ('comunidad_nombre_recibo', models.CharField(max_length=150, verbose_name='Comunidad en recibo')),
                ('codigo_productor_recibo', models.CharField(max_length=20, verbose_name='Código del productor en recibo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_cafe', to='comunidades.comunidad', verbose_name='Comunidad')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_cafe_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_cafe', to='productores.productor', verbose_name='Productor')),
            ],
            options={
                'verbose_name': 'Compra de café',
                'verbose_name_plural': 'Compras de café',
                'db_table': 'compras_cafe',
                'ordering': ['-fecha_compra', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetallePesajeCompra',
            fields=[
                ('id_detalle_pesaje', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_libras', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad de libras')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesajes', to='compras.compracafe', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Detalle de pesaje',
                'verbose_name_plural': 'Detalles de pesajes',
                'db_table': 'detalles_pesaje_compra',
            },
        ),
    ]
